apiVersion: v1
kind: Secret
metadata:
  name: objects-creds
  namespace: default
type: Opaque
stringData:
  ACCESS_KEY_ID: B6ODA73M8VJBVRNVTBRO
  ACCESS_SECRET_KEY: GdfRBnOoSfNMAtAVwVHUyikXwDvK0VZ4Pohra0ht
