apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: opentelemetry-collector
spec:
  clusterIP: None  # Headless service for DaemonSet
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
  - name: metrics
    port: 8889  # Match the port used by the Prometheus exporter
    targetPort: 8889
    protocol: TCP
