apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:17.4'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-built-in-list-extensions
            - configMapRef:
                name: postgres-built-in-sql-extensions
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
