---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: j2pw3e.br6cd8ffcody4lrl
    ttl: 24h0m0s
    usages:
      - signing
      - authentication

certificateKey: 4bc59df803b8048d9327effebc40e07a1f067d5337e61dda6c5f54b3523758bd
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  taints: null

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
apiServer:
  certSANs:
    - "135.181.102.58"         # Public IP of HAProxy
    - "127.0.0.1"              # Loopback
    - "10.0.0.14"              # Private IP of HAProxy
    - "lb.veryeasy.dev"        # DNS name of HAProxy
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: "lb.veryeasy.dev:6443"
controllerManager: {}
dns: {}
etcd:
  external:
    endpoints:
      - "https://10.0.0.4:2379"
      - "https://10.0.0.5:2379"
      - "https://10.0.0.6:2379"
    caFile: "/etcd/kubernetes/pki/etcd/ca.pem"
    certFile: "/etcd/kubernetes/pki/etcd/etcd.pem"
    keyFile: "/etcd/kubernetes/pki/etcd/etcd-key.pem"
imageRepository: registry.k8s.io
kubernetesVersion: 1.31.7
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}

