---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: xa28p3.yuoamcyx4clpbsgd
  ttl: 24h0m0s
  usages:
  - signing
  - authentication

certificateKey: bbf1878304d89db6f2f68af5eefba7c46859b5dda07dbe09739a5734dce293a9
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  taints: null
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
apiServer:
  certSANs:
    - "135.181.102.58"
    - "127.0.0.1"
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  external:
    endpoints:
      - "https://192.168.1.10:2379"
      - "https://192.168.1.11:2379"
      - "https://192.168.1.12:2379"
    caFile: "/etc/etcd/pki/ca-cert.pem"
    certFile: "/etc/etcd/pki/cluster-cert.pem"
    keyFile: "/etc/etcd/pki/cluster-key.pem"
imageRepository: registry.k8s.io
kubernetesVersion: 1.31.7
controlPlaneEndpoint: "135.181.102.58:6443"
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}
