#kind: "postgresql"
kind: "Cluster"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "postgres-timescaledb-deployment-cluster"
  namespace: "postgres-timescaledb-deployment"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "17"
  numberOfInstances: 3
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  enableConnectionPooler: true
  enableReplicaConnectionPooler: true
  enableMasterPoolerLoadBalancer: true
  enableReplicaPoolerLoadBalancer: true
  maintenanceWindows:
  volume:
    size: "10Gi"
    storageClass: "postgres-timescaledb-storageclass"
    iops: 6000
    throughput: 256
  users:
    postgres: []
  databases:
    timescaledb: postgres
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
